plugins {
    id 'java-library'
    id 'net.neoforged.moddev' version '2.0.141'
    id "com.modrinth.minotaur" version "2.+"
    id 'maven-publish'
}

repositories {
    maven { url = "https://api.modrinth.com/maven" }
}

base {
    archivesName = project.archives_base_name
}
version = project.mod_version + '+' + project.minecraft_version
group = project.maven_group

java.toolchain.languageVersion = JavaLanguageVersion.of(25)

neoForge {
    version = project.neo_version

    runs {
        client {
            client()
        }

        server {
            server()
            programArgument '--nogui'
        }
    }

    mods {
        "${mod_id}" {
            sourceSet(sourceSets.main)
        }
    }
}

dependencies {
    jarJar(implementation("maven.modrinth:midnightlib:${project.midnightlib_version}-neoforge")) {
        version {
            strictly "[${project.midnightlib_version}-neoforge,)"
            prefer "${project.midnightlib_version}-neoforge"
        }
    }
}

processResources {
    inputs.property "version", project.version

    filesMatching("META-INF/neoforge.mods.toml") {
        expand "version": project.version, "minecraft_version_range": project.minecraft_version_range
    }

    from("src/main/resources/data/sleepwarp/lang") {
        into("assets/sleepwarp/lang")
    }
}

java {
    withSourcesJar()
}

jar {
    from("LICENSE") {
        rename { "${it}_${project.archives_base_name}" }
    }
}

if (System.getenv("MODRINTH")) {
    modrinth {
        token = System.getenv("MODRINTH")
        projectId = 'DlSXkZVT'// The ID of your modrinth project, slugs will not work.
        versionNumber = "" + version // The version of the mod to upload.
        versionType = "beta"
        uploadFile = jar // This links to a task that builds your mod jar and sets "uploadFile" to the mod jar.
        gameVersions = [((String) project.minecraft_version)]
        changelog = System.getenv("CHANGELOG")
        loaders = ["neoforge"]

        dependencies {
            required.project "midnightlib"
        }
    }

    jar {
        finalizedBy project.tasks.modrinth
    }
}
